services:
  chatappbe:
    image: chat_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    # environment:
    #   DB_HOST: postgres
    #   DB_USER: user
    #   DB_PASSWORD: password123
    #   DB_NAME: chat_db
    #   DB_PORT: 5432
    #   DB_TZ: Asia/Jakarta
    #   JWT_KEY: secretChatApi
    #   JWT_EXP: 60

  postgres:
    image: postgres:16
    container_name: chat_app_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chat_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
